version: '3.9'

services:
  rtsp-proxy:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: rtsp-hls-proxy
    restart: unless-stopped
    ports:
      - "3010:3000"
      - "8090:8080"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - WS_PORT=8080
    volumes:
      - /volume1/docker/rtsp-proxy/app:/app
      - /volume1/docker/rtsp-proxy/streams:/app/streams
      - /volume1/docker/rtsp-proxy/logs:/app/logs
    working_dir: /app
    command: >
      sh -c "
      apk add --no-cache ffmpeg &&
      if [ ! -d node_modules ]; then
        echo 'Installing dependencies...' &&
        npm install
      fi &&
      echo 'Starting server...' &&
      node server.js
      "
    healthcheck:
      test: curl -f http://localhost:3010/health || exit 1



      